### ISSUE TITLE
对gcc还要linux内核版本有要求吗

### ISSUE THREAD

**Issue by ChiuJun** [sheisc/ucc162.3#7]
在Windows虚拟机下折腾了半天，都是按要求设置的，最后跑hello的时候显示memory exhausted；
在Linux下运行 make test 的时候报了一堆的错
我的gcc版本
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

**Comment by ghost** [comment]
如果编译运行ucc存在问题，请尝试使用由作者提供的已搭建好环境的**虚拟机映像**。
虚拟机映像的**网盘**下载地址在[这个博文](https://blog.csdn.net/SheIsC/article/details/42394967)中（文中红色字体部分）。

**Comment by ChiuJun** [comment]
非常感谢，问题解决了。
